const english={
      "PropertyPaneDescription": "Helpdesk 365 is Microsoft 365 ticketing system, that ensures your organization can handle every issue effectively with specific help requests (e.g. IT, HR, Finance).",
      "BasicGroupName": "HR365",
      "DescriptionFieldLabel": "Description",
      //Teams & TeamsEdit Component
      "TextFieldName":"Name",
      "TextFieldCode":"Code",
      "TextFieldSupervisor":"Supervisor",
      "TextFieldTeamMembers":"Team Members",
      "TextFieldDefaultTeam":"Default Team",
      "Save":"Save",
      "New":"New",
      "Edit":"Edit",
      "EnterNamesorEmailadresses":"Enter Names or Email adresses..",
      "Filterbyname":"Filter by Name:",
      "Action":"Action",
      "Addbutton":"Add",
      "Update":"Update",
      "EditTeams": "Edit Team",
      "AddTeams": "Add Team",
      "AddPhone": "Add Phone",
      "EditPhone": "Edit Phone",
      "EditCannedResponse": "Edit Canned Response",
      "EditMyCannedResponse": "Edit My Canned Response",
      "EditMySignature": "Edit My Signature",
      "ColumnName": "Column Name",
      "SubColumn": "Sub Column",
      "Type1": "Column Type",
      "ColCategory":"Column Category",
      "ColActive":"Active",
      "EditColumn": "Edit Column Name",
      "PleaseProvideatLeastColumnName":"Please Provide Column Name.",
      "AddMore":"Save & Add More",
      "Columnalreadyexists":"Column already exists.",
  
      "policyName":"Enter Policy Name",
      "defineName":"Enter Policy Description",
  
      //Edit Choice
  
      "Choice":"Choice",
  
      //Custom Settings
      "DateFormats":"Date Format",
      "RenameDisplayTitle":"Rename Display Title",
      "RenameCompanyName":"Rename Company Name",
      "RenameTicketTitle": "Rename Ticket Title",
      "SurveyLinkValidation":"Survey Link Validation",
      "TicketsCanbeDeletedBy":"Tickets Can be Deleted By",
      "Admin":"Admin",
      "Agent":"Agent",
      "IntegrateAssetManagementPluswithHelpdeskPlus":" Integrate Asset Management with Helpdesk",
      "codeasticketsuffix":"Code as Ticket Suffix",
      "Displayresolvedtabsinhomepage":"Display Resolved Tabs in Homepage",
      "EnableTicketMailbox":"Enable Ticket Mailbox",
      "AutoCloseTickets":"Auto Close Tickets",
      "AutoAssignTickets":"Auto Assign Tickets",
      "BrandLogo":"Brand Logo",
      "CustomNote":" Note : Please upload logo with size of 150 X 60 px or less in same aspect ratio for better results, please use transparent background & white color for better viewing experience",
      "UploadLogo":"Upload Logo",
      "Crop":"Crop",
      "SaveLogo":"Save Logo",
      "DarkMode":"Dark Mode",
      "SideNavBarHide":"Hide Side Navigation Panel on Sharepoint Page",
      "HideWebPartTitle":"Hide Webpart Title on Sharepoint Page",
      "TeamsCodeasTicketSuffix": "Teams code as ticket suffix",
      "AutoAssignMethod": "Auto Assign Method",
      "DisableCustomWebpartCss": "Disable custom webpart CSS",
      "HideWebpartTitle": "Hide webpart title on sharepoint page where app is running",
      "SideNavigationTheme": "Side Navigation Theme ",
      "HideSideNavigationPanel" : "Hide side navigation panel on sharepoint page where app is running",
      "PleaseEnsureThatIntegrationRequiresexternaldatabasePathtobeenabledinAssetManagement": "Please ensure that integration requires external database path to be enabled in Asset Management 365",
      "Allowagentstosettheiravailability": "Allow agents to set their availability",
      "SubjectLineKeywords": "Subject Line Keywords",
      "BodyLineKeywords": "Body Line Keywords",
      "ExcludeAgentsfromAutoAssign":"Exclude Agents from Auto Assign",
      "UnAvailableUsers": "UnAvailable Users",
      //Web Form Fields
      "AllowUserstosetthe":"Allow Users to Set The",
      "Allowusertosetthepriority":"Allow Users to Set The Priority",
      "Allowusertosettherequesttype":"Allow Users to Set The Request Type",
      "Allowusertosettheservice":"Allow Users to Set The Service",
      "AllowusertosettheRequest":"Allow Users to Set The Requester",
      "AllowusertosettheTitle":"Allow Users to Set The Title",
      //MasterSideNav
      "Home":"Home",
      "Settings":"Settings",
      "Help":"Help",
      "Dashboard":"Dashboard",
      "Reports":"Reports",
      "CustomSettings":"Custom Settings",
      "WebFormFields":"Web Form Fields",
       //new ticket
      "NewTicket":"Ticket",
      "GeneralSetting": "General Setting",
      "Users":"Users",
      "Teams":"Teams",
      "Services":"Services",
      "BusinessHours":"Business Hours",
      "Pleaseenterbusinesshoursname": "Please enter business hours name",
       "ServiceName" : "Service Name",
      "AddBulk" : "Add Bulk",
      //Homepage
      "AddNewTicket": "Add New Ticket",
      "SyncMailbox":"Sync Mailbox",
      "Report": "Report",
      "Unassigned": "Unassigned",
      "TeamsTickets": "Teams Tickets",
      "TeamsClosed": "Teams Closed",
      "TicketMailbox":"Ticket Mailbox",
      "MyTickets":"My Tickets",
      "RequestedByMe": "Requested by Me",
      "MyClosed":"My Closed",
      "MyResolved": "My Resolved",
      "TeamsResolved": "Teams Resolved",
      "ResolvedDate": "Resolved Date",
      "Resolvedby": "Resolved By",
      "Show":"Show",
      "Tickets": "Tickets",
      "Search":"Search",
      "Previous":"Previous",
      "Next":"Next",
      "CommentPanel":"Comment Panel",
      "Showing":"Showing",
      "Of":" of ",
      "Pages":"pages",
      "to":"to",
      "Items": "items",
      "Entries": "entries",
  
      "Teams":"Teams",
      "TicketId": "Ticket ID",
      "Title":"Title",
      "Status": "Status",
      "Priority": "Priority",
      "RequestedBy": "Requested By",
      "AssignedTo": "Assigned To",
      "CreatedDate":"Created Date",
      "CreatedBy": "Created By",
      "Agehm": "Age hh:mm",
      "Age": "Age",
      "Action": "Action",
      "ClosedDate":"Closed Date",
      "Days":"Days",
      "ClosedBy":"Closed By",
      "Form":"Form",
      "Subject":"Subject",
      "Body":"Body",
      "SyncMailbox": "Sync Mailbox",
      "Send":"Send",
      //Add New Ticket in Homepage
      "RequestType": "Request Type",
      "Requester": "Requester",
      "Submit": "Submit",
      "TicketDescreption": "Ticket Descreption",
      "Low": "Low",
      "High": "High",
      "Medium": "Medium",
      "Urgent": "Urgent",
      "Question": "Question",
      "Problem": "Problem",
      "Incident": "Incident",
      "Request": "Request",
  
      //Canned Response
      "AddNew": "Add New",
      "GlobalCannedResponse": "Global Canned Response",
      "MyCannedResponse": "My Canned Response",
      "MySignature":"My Signature",
      "ShowEntries": "Entries",
      "Yes": "Yes",
      "No": "No",
      "Main": "Main",
      "Members": "Members",
      "EditRecords": "Edit Records",
      "AddCannedResponse": "Add Canned Response",
      
      "SomethingWentWrong": "Something went wrong!",
      "DeleteAlertMessage":"Are you sure you want to delete the row?",
      "DeleteAlertMessagepolicy":"Are you sure you want to delete this policy?",
      "DeleteAlertMessageCustomColumn":"Are you sure you want to delete the custom coulmn?",
      "DeleteAlertMessage2":"Are you sure you want to delete this user?",
      "DeleteAlertMessageservice":"Are you sure you want to delete this",
      "DeleteAlertMessagepriority":"Are you sure you want to delete this priority?",
      "DeleteAlertMessageteam":"Are you sure you want to delete this team?",
      "DeleteAlertMessageRequest":"Are you sure you want to delete this request?",
      "DeleteAlertMessageBusinessHour":"Are you sure you want to delete this business hours?",
      "DeleteAlertMessagemailbox": "Are you sure you want to delete the manager mailbox?",
      "DeleteAlertMessageTeams": "Are you sure you want to delete the team?",
      "DeleteAlertMessagestatus": "Are you sure you want to delete the status?",
      // "DeleteAlertMessageservice": "Are you sure you want to delete the service?",
      // "DeleteAlertMessagesubservice": "Are you sure you want to delete the sub service?",
      "DeleteAlertMessageColumn":"Are you sure you want to delete this column?",
      "DeleteAlertMessageTicket" : "Are you sure you want to delete this ticket?",
       "TimeTrack" : "Please enter time in minutes",
       "EmptytimeTrackBox": "Please enter time to track.",
       "Timetrackingismandatory": "Time tracking is mandatory.",
       "Areyousureyouwanttostoptimetracking": "Are you sure you want to stop time tracking?",
       "Unassignedticketnotresolved": "Unassigned ticket can not be resolved.",
       "Unassignedticketnotclosed": "Unassigned ticket can not be closed.",
       "UpdateTitle":"Update",
      "Department": "Department",
      "ManagerName": "Manager Name",
      "Location": "Location",
      "GlobalCannedResponseTitle": "Global Canned Response Title",
      "CannedResponseTitle": "Canned Response Title",
      "GlobalCannedMessage": "Global Canned Message",
  
      "MyCannedResponseTitle": "My Canned Response Title",
      "MyCannedResponse":"My Canned Response",
      "MyCannedMessage": "My Canned Message",
  
      "MySignatureTitle": "My Signature Title",
      "SignatureTitle": "Signature Title",
      "SignatureMessage": "Signature Message",
  
      "TitleAlreadyExists": "Title already exists",
      "EnterTitle ": "Enter title ",
      "SavedSuccessfully": "Saved successfully!",
      "PleaseenterglobalCannedResponseTitle":"Please enter global canned response title",
      "PleaseentermyCannedResponsetitle" : "Please enter my canned response title",
      "PleaseEnterthePhoneNumber": "Please enter the phone number",
      "PleaseProvideRequestType":"Please provide request type",
      "PleaseProvideatLeastOneService": "Please provide at least one",
      "PleaseProvideatLeastOneStatus": "Please provide at least one status",
      "EditStatus": "Edit Status",
  
      //Customer Satisfaction
      "NewSurvey": "New Survey",
      "EditSurvey": "Edit Survey",
      'EmailsSentAfterATicketIsClosed': 'Emails sent once ticket is "Closed".',
      'EmailsSentAfterATicketIsResolved': 'Emails sent once ticket is "Resolved".',
      'AllowAgentsToSendSurveyLink': 'Allow agents to send survey link.',
      "SurveyName": "Survey Name",
      "CustomerSatisfactionSurvey": "Customer Satisfaction Survey",
      "QuestionMessage": "This question helps assess the overall satisfaction for the response provided by the agent. It appears below your signature at the bottom of the email sent to the customer.",
      "SurveyQuestion":"Survey Question",
      "SurveyPlaceholder": "How would you rate your overall satisfaction for the resolution provided by the agent?",
      "ThankyouPage":"Thank You Page",
      "YourPortalLayoutwillbeappliedtoThisPage": "Your portal layout will be applied to this page.",
      "ThankyouMessageforCustomerSatisfactionSurvey": "Thank you message for customer satisfaction survey",
      "ThankyouforyourValueableFeedback": "Thank you for your valueable feedback.",
      "IncludeCommentsBox": "Include comments box",
      "WhichEmailsshouldhavetheSatisfactionSurveyLink": "Which emails should have the satisfaction survey link?",
      "Cancel": "Cancel",
      "PleaseProvideaSurveyName" : "Please provide a survey name",
      "PointScale": "Point Scale",
      "Satisfied":"Satisfied",
      "MostlySatisfied": "Mostly Satisfied",
      "SomewhatSatisfied": "Somewhat Satisfied",
      "Fair":"Fair",
      "SomewhatDissatisfied": "Somewhat Dissatisfied",
      "MostlyDissatisfied": "Mostly Dissatisfied",
      "Dissatisfied": "Dissatisfied",
      "PleaseProvideatLeastOneChoice":"Please Provide atLeast One Choice.",
  
  
      //CannedResponse Panel
      "CannedResponse": "Canned Response",
      "Add": "Add",
  
      //Comments
      "HumanResources": "Human Resources",
      "InformationTechnology": "Information Technology",
      "Support": "Support",
      "SalarySlip":"Salary Slip",
      "AddressChange":"Address Change",
      "Office365":"Office 365",
      "HardwareIssue":"Hardware Issue",
      "Pending":"Pending",
      "Resolved":"Resolved",
      "WaitingOnCustomer":"Waiting on Customer",
      "WaitingonThirdParty":"Waiting on Third-Party",
      "Closed": "Closed",
      "Open":"Open",
      "UnassignedTicketCannotBeClosed":"Unassigned ticket cannot be closed.",
      "Replyseemstobeblankdoyouwanttosend":"Reply seems to be blank, do you want to send?",
      "UpdateAndsetasPending":"Update and set as pending",
      "UpdateAndsetasResolved":"Update and set as resolved",
      "UpdateAndsetasClosed":"Update and set as closed",
      "UpdateAndsetasWaitingonCustomer":"Update and set as waiting on customer",
      "UpdateAndsetasWaitingonThirdParty":"Update and set as waiting on third party",
      "PleaseAssignTheTicketToMerge":"Please assign the ticket to merge!",
      "AreYouSureyouwanttomergeticket": " Are you sure want to merge ticket?",
      "AreYouSureYouWantToSplitTheTicket":"Are you sure you want to split the ticket?",
      "AreYouSureYouWantToCreateANewTicket":"Are you sure you want to create a new ticket",
      "ModifiedBy":"Modified By",
      "Reply": "Reply",
      "ClearFilters": "Clear Filters",
      "AddPrivateNote": "Private Note",
      "Consult": "Consult",
      "Transfer": "Transfer",
      "Merge":"Merge",
      "Split": "Split",
      "Create": "Create",
      "SolidUp": "Sort ticket thread",
      "Attachment": "Attachment(s)",
      "AttachmentTitlle": "Click on the attachment icon to add multiple attachments",
      "downloadtitle":"Export ticket details as PDF",
      "Discard":"Discard",
      "Type": "Type",
      "PropertiesHelpTitle": "When a ticket is opened/replied using helpdesk email with email id(s) in Cc, will show up here for display purpose only.",
      "TicketHistory":"Ticket History",
      "Clickhere":"Click here",
      "ContactDetails": "Contact Details",
      "EmailId": "Email Id",
      "Phone":"Phone #",
      "Job":"Job",
      "RecentTickets":"Recent Tickets",
      "Ok": "Ok",
      "Properties": "Properties",
      "OldValue": "Old Value",
      "NewValue": "New Value",
      "ModifiedOn": "Modified On",
  
      //DashBoard
     
      "CurrentWeek": "Current Week",
      "LastWeek": "Last Week",
      "CurrentMonth":"Current Month",
      "LastMonth": "Last Month",
      "PreviousMonth":"Previous Month",
      "All": "All",
      "ModifiedDate": "Modified Date",
      "Positive": "Positive",
      "Negative": "Negative",
      "Neutral": "Neutral",
      "Total": "Total",
      "From": "From",
      "To": "To",
      "Year": "Year",
      "Quarter": "Quarter",
      "Month": "Month",
      "Filteroption": "Filter Option",
      "OpenVSClosed": "Open VS Closed",
      "TotalTicketStatus": "Total Ticket Status",
      "TotalTickets": "Total Tickets",
      "AgentReport" : "Agent Report",
      "NoDataAvailable": "No data available",
      "NoDataToDisplay": "No data to display",
      "CustomerSatisfaction": "Customer Satisfaction",
      "Active": "Active",
      "Placeholders": "Placeholders",
      "EmailSubject": "Email Subject",
      "TicketFields": "Ticket Fields",
      "RequesterName": "Requester name",
      "RequesterEmail": "Requester email",
  
      //EditEmailNotification
      "Trigger":"Trigger",
      "EmailBody": "Email Body",
      "IsActive": "Is Active",
      "Assignee": "Assignee",
      "Supervisor": "Supervisor",
      "SatisfactionSurveyStarRating" : "Satisfaction Survey with Star Rating",
  
  
      "Description": "Description",
      "TicketURL": "Ticket URL",
      "LastPublicComment": "Public Comments",
      "AgentName": "Agent Name",
      "AgentEmail": "Agent Email",
      "SatisfactionSurvey": "Satisfaction Survey",
      "MergeTicketID": "Merge Ticket ID",
      "SplitTicketID": "Split Ticket ID",
      "TicketType": "Ticket type",
  
      //Add For service
      "Select":"Select",
      "Default": "Default",
      "TeamsName": "Teams Name",
      "TeamName": "Team Name",
      "AddServices": "Add Services",
      "NewServices": "New Services",
      "DefaultService": "Default Service",
      "TeamsCode": "Teams Code",
      "TeamCode": "Team Code",
      "PleaseProvideatLeastOneService" : "Please provide at least one",
  
      //Phone
      "EditPhones":"Edit Phones",
      "TeamsHelpDeskPhoneNumber": " Helpdesk Phone Number",
      "AddedSuccessfully": "Added successfully!",
      "UpdatedSuccessfully": "Updated successfully!",
  
      //Request Type
      "DeletedSuccessfully": "Deleted successfully!",
      "RestordSuccessfully": "Ticket restored successfully!",
  
      "DataSavedSuccessfully": "Data saved successfully!",
      "PleaseFillTheRequiredFields": "Please fill the required fields!",
  
      "PleaseAddOnePriority": "Please add one priority",
      "DefaultRequestType": "Default Request Type",
      "AddNewRequestType": "Add New Request Type",
      "AddRequestType": "Add Request Type",
      "ErrorWhileSavingDataPleaseTryAgainAfterSometime": "Error while saving data, please try again after sometime.",
      "SavingPleaseWait": "Saving please wait..." ,
      "DefaultRequest": "Default Request",
  
      "AddPriority":"Add Priority",
      "PriorityType": "Priority Type",
      "EditRequestType": "Edit Request Type",
      "AddNewPriority": "Add New Priority",
      "AddNewStatus": "Add New Status",
      "DefaultType": "Default Type",
      "DefaultPriorityType": "Default Priority Type",
      "DefaultStatus": "Default Status",
      "EditPriority": "Edit Priority",
      "TicketName": "Ticket Name",
      "TicketPrefix": "Ticket Prefix",
      "SaveAndAdd": "Save and Add",
  
      "EnterTicket": "Enter ticket ",
      "TeamAlreadyExists": "Team Already Exists",
  
      "On": "On",
      "Off": "Off",
      "InfoTitle": "All the email from these domains and email ids are used to craeted outlook rules which enable ticket creation.",
  
      "NoOfDaysToLinkExpire": "No. of days to link expire",
      "CompanyName": "Company Name",
      "Use": "Use",
  
      //MailBox
      "ManagerMailbox": "Manager Mailbox",
      "CreateAutomaticTickets": "Create Automatic Tickets",
      "TicketMailBox": "Ticket Mail Box",
      "infoTitleTicketMailBox": 'This is a helpdesk premium feature, to add/change ticket mailbox id please write to appsupport@hr365.us',
      "AllowedDomains": "Allowed Domains",
      "InfoTitleAllowedDomains": "All the email from these domains and email ids are used to craeted outlook rules which enable ticket creation.",
      "AllowedExternalDomains": "Allowed External Domains",
      "InfoTitleExternalDomains": "For these external domains the email notification will be triggered",
      "MailboxManager": "Mailbox Manager",
      "InfoTitleMailboxManager": "This is an add-on role and it enable view ticket mailbox tab on homepage.",
      //Users
      "SyncfromM365": "Sync from M365",
      "ToupdateuserpropertiesfromM365clickheretoSync": "To update user properties from M365, click here to sync",
      "EditUsers": "Edit Users",
      "AddUsers": "Add Users",
      "AddBulkUsers": "Add Bulk Users",
      "ManagerEmail": "Manager Email",
      "JobTitle": "Job Title",
      "Role": "Role",
      "Email": "Email",
      "GlobalAccess": "Global access - Can view all tickets in the helpdesk.",
      "TeamAccessI": "Team access I - Can view tickets assigned to all team(s) in unassigned tab, tickets assigned to him/her. Assign tickets to all team(s).",
      "TeamAccessII": "Team access II - Can view tickets assigned to their team(s) in unassigned tab, tickets assigned to him/her. Assign tickets to their team(s).",
      "RestrictedAccess": "Restricted access - Can view tickets assigned to him/her. Team tickets detailed view will not be available.",
      "EnterName": "Enter Name",
      "Roles": "Roles",
      "RolesAndScopes": "Roles and scopes",
      "User": "User",
      "EditServices": "Edit Services",
      "RolesandScopes" : "Roles and scopes",
      "EntereduseralreadyexistsPleaseaddaNewUser": "Entered user already exists. Please add a new user",
      "PleaseEnterMyCannedResponseTitle": "Please enter my canned response title",
      "PleaseProvidePriority": "Please provide priority",
      "Pleaseprovideavalidpriority":"Please provide a valid priority",
      "PleaseProvideanewvalidrequesttype":"Please provide a new valid request type",
      "Pleaseentertheteamname":"Please enter the team name",
      "Pleaseentertheteamcode":"Please enter the team code",
      "OrderTicketFields": "Order Ticket Fields",
      "TicketNameTictle": "eg: Ticket, SR, Issue, Service, Request..",
      "EntertheTicketName": "Enter the ticket name",
      "SequenceTitle" : "eg: 1000, 560000, 100RX00..",
      "AbovePriorityalreadyexistsPleaseAddanewpriority":"Above priority already exists. Please add a new priority!",
      "AboveCustomFormisAlreadyExisting":"Above ticket request form already exists. Please add a new ticket request form!",
      "AbovePriorityalreadyexistsPleaseAddanewSubService":"Above Sub Service already exists. Please add a new Sub Service!",
      "EditEmailBody": "Edit Email Body",
      "TicketDescription":" Info captured with these fields will be stored as part of ticket description.",
      "TicketProperty":"Info captured with these fields will be stored as ticket properties and will be available under home and reports data tables.",
       "SubColumnValues":"Please mention your choices separated with comma (,).",
      "UseTeamsCodeasTicketSuffix":"Teams code as ticket suffix",
      "EnableSubTicket":"You can create a sub ticket when the feature is turned on.",
      "EnableTimeTracking":"You can track time spent on a ticket if this feature is turned on.",
      "RenameApplicationTitle":"Change app title which is visible on top bar, can be changed to text of your choice.",
      //Reports
      "SelectTeams": "Select Teams",
      "SelectStatus": "Select Status",
      "SelectAgent": "Select Agent",
      "Today" : "Today",
      "LastDay": "Last Day",
      "SelectPriority": "Select Priority",
      "CusSatRating": "CusSat Rating",
      "Comments": "Comments",
      //SettingPage
      "GeneralSettings": "General Settings",
      "BusinessHours": "Business Hours",
      "TicketSequence": "Ticket Sequence",
      "SupportChannel": "Support Channel",
      "HelpDeskMailBox": "Helpdesk MailBox",
  
      "HelpDeskProductivity": "Helpdesk Productivity",
      "CannedResponses": "Canned Responses",
      "EmailNotification": "Email Notification",
      "CustomerSatisfaction": "Customer Satisfaction",
  
      "SiteTheme": "Site Theme",
      "LightMode": "Light Mode",
      "RemoveCustomWebpartCss": "Remove Custom Webpart CSS",
      "Ticketsspace": " Tickets",
      "Closedspace": " Closed",
      "Resolvedspace": " Resolved",
      "Selectspace": "Select ",
      "EditBusinessHours" : "Edit Business Hours",
      "Sunday" : "Sunday",
      "Monday": "Monday",
      "Tuesday" : "Tuesday",
      "Wednesday" : "Wednesday",
      "Thursday": "Thursday",
      "Friday": "Friday",
      "Saturday": "Saturday",
      "HelpdeskHours" : "Helpdesk Hours",
      "SelectWorkingDaysHours" : "Select working days/hours",
      "hrs24x7Days": "24 hrs x 7 days",
      "PleaseEnterGlobalCannedResponseTitle": "Please enter global canned response title",
      "PleaseEnterMyCannedResponseTitle": "Please enter my canned response title",
      "PleaseEnterSignatureTitle": "Please enter signature title",
      "ExporttoExcel":"Export to Excel",
      "Delete":"Delete",
      "Assigned":"Assigned",
      "SettingSavedSuccesfully": "Setting saved successfully!",
      "SLAPoliciesApplied" : "SLA Policies Applied",
      "UserIconTitle": "Here you can add admins, supervisors and agents. Other Microsoft 365 helpdesk users are getting inherited access through SharePoint level. There is no need to add them manually.",
      "TicketFieldTitle" : "If field is disabled then default value will be selected for that field in new ticket form.",
      "SubServiceName": "Sub Service Name",
      "SubService": "Sub Service",
      "SubTicket": "Sub Ticket",
      "Review": "Review",
      "Escalate": "Escalate",
      "Review": "Review",
      "PleaeEntertitle": "Please enter new title.",
      "Validate": "Validate",
      "TicketPropertiescanhideShowintheUsersCommentPage":"Ticket Properties can hide/show in the users' comment page",
      "TicketPropertiescanhideShowintheMembersCommentPage": "Ticket Properties can be hide/show in members (admin, supervisor, and agent) comment page",
      "SyncUserPropertiesfromM365": "Sync will update the user properties (department, job title, location, etc.) of the existing users from the M365.",
      //Assets:
      "AssignedAssets":"Assets Assigned",
      "AssetDeailsHeading": "Asset Details",
      "Cost": "Cost",
      "ResidualCost": "Residual Cost",
      "BarcodeOrQRCode": "Bar Code / QR Code",
      "AssetId": "Asset ID",
      "Documents": "Documents",
      "Additional": "Additional",
      "CurrentUser": "Current User",
      "UserLocation": "User Location",
      "UserDepartment": "User Department",
      "ExportQRCodes": "Export QR Codes",
      "ExportBarcodes": "Export Barcodes",
      "OrganizationName": "Organization Name",
      "ReturnDate": "Return Date",
      "AssignDate": "Assign Date",
      "NumberOnly": "Only numeric values allowed",
      "CommaSpearate": "Please mention your choices separated with comma (,)",
      "General": "General",
      "Print": "Print",
      "AssetNameErrorMessage": "Enter the asset name",
      "AssetExpiryNotification": "Asset Expiry Notification",
      "UploadCommercialDocument": "Upload Commercial Document",
      "AssetName": "Asset Name",
      //MOBILE VIEW
      "MyRequestes": "My Requests",
      "Requests": "Requests",
      "Knowledgebase": "Knowledgebase",
  
      //Feedback submission
      "Feedbacksubmittedsuccessfully": "Feedback has been submitted successfully!",
  
      /////// For language part
  
      ////Deshboard
      "Satisfied":"Satisfied",
      "MostlySatisfied":"MostlySatisfied",
      "MostlySatisfied":"Mostly Satisfied",
      "SomewhatSatisfied":"Somewhat Satisfied",
      "Dissatisfied":"Dissatisfied",
      "Mostlydissatisfied":"Mostly dissatisfied",
      "SomewhatDissatisfied":"Somewhat Dissatisfied",
      "Portal":"Portal",
      "Email":"Email",
      "Phone":"Phone",
      "Forms":"Forms",
      "Bot":"Bot",
      "Others":"Others",
      "CurrentWeekForkey": "CurrentWeek",
      "CurrentMonthForKey":"CurrentMonth",
      "CurrentQuarterForKey":"CurrentQuarter",
      "CurrentQuarter":"Current Quarter",
      "CurrentYear":"Current Year",
      "CurrentYearForkey":"CurrentYear",
      "LastWeekForkey": "LastWeek",
      "LastMonthForkey": "LastMonth",
      "LastQuarterForkey":"LastQuarter",
      "LastQuarter":"Last Quarter",
      "LastYearForkey":"LastYear",
      "LastYear":"Last Year",
      "CustomDate":"Custom Date",
      "CustomDateForkey":"CustomDate",
      "CustomYear":"Custom Year",
      "CustomYearForkey":"CustomYear",
      "CustomQuarter":"Custom Quarter",
      "CustomQuarterForkey":"CustomQuarter",
      "CustomMonth":"Custom Month",
      "CustomMonthForkey":"CustomMonth",
      "CustomWeekForkey":"CustomWeek",
      "CustomWeek":"Custom Week",
      "January":"January",
      "February":"February",
      "March":"March",
      "April":"April",
      "May":"May",
      "June":"June",
      "July":"July",
      "August":"August",
      "September":"September",
      "October":"October",
      "November":"November",
      "December":"December",
      "Created":"Created",
      "Escalated":"Escalated",
      "TicketsThisMonth":"Tickets This Month",
      "AllTeams" :"All Teams",
      "SLAResponseAverage":"SLA Response - Average",
      "SLAResponseWeekdays":"SLA Response - Weekdays",
      "TicketsByType":"Tickets by Type",
      "OpenTicketsDepartment":"Open Tickets by Department",
      "TicketsPriority":"Tickets by Priority",
      "TicketsSource":"Tickets by Source",
      "TimeTrack":"Time Track",
      "SLAResolveAverage":"SLA Resolve - Average",
      "SLAResolveWeekdays" :"SLA Resolve - Weekdays",
      "ApplyFilter":"Apply Filter",
      "Filterapplied":"Filter applied successfully!",
      "SelectStartDate":"Please select the Start Date",
      "SelectEndDate":"Please select the End Date",
      "selectleastonefield":"Please select at least one field",
      "SelectOption":"Select Option",
      "SelectDatebtu":"Select a date. Input format is day slash month slash year.",
      "StartDate":"Start Date:",
      "EndDate":"End Date:",
      "SelectYear":"Select Year",
      "SelectQuarter":"Select Quarter",
      "SelectMonth":"Select Month",
  
      ///help Page 
  
      "LicenseType":"License Type : ",
      "Expired":"(Expired)",
      "ValidTill":"Valid till : ",
      "LicenseTypeExpired":"License Type : Expired",
      "LicenseTypeLimited":"License Type : Limited",
      "LicenseTypeStandardPerpetual":"License Type : Standard (Perpetual)",
      "LicenseTypeStandardExpired":"License Type : Standard (Expired)",
      "LicenseTypeStandard":"License Type : Standard",
      "LicenseTypePlusPerpetual":"License Type : Plus (Perpetual)",
      "LicenseTypePlusExpired":"License Type : Plus (Expired)",
      "LicenseTypePlus":"License Type : Plus",
      "LicenseTypePremiumPerpetual":"License Type : Premium (Perpetual)",
      "LicenseTypePremiumExpired":"License Type : Premium (Expired)",
      "LicenseTypePremium":"License Type : Premium",
      "LicenseTypeEnterprisePerpetual":"License Type : Enterprise (Perpetual)",
      "LicenseTypeEnterpriseExpired":"License Type : Enterprise (Expired)",
      "LicenseTypeEnterprise":"License Type : Enterprise",
      "Inputlicensekey":"Please input license key!",
      "HD365":"HD365",
      "LicenseValidationSuccessful":"License validation successful!",
      "EnterLicenseKey":"Please enter valid license key!",
      "ValidatedSuccessfully":"License has been validated successfully!",
      "ContactUs":"Contact Us",
      "PrivacyPolicy":"Privacy Policy",
      "FAQ":"FAQ",
      "ProductActivation":"Product Activation",
      "PleaseWait":"Please wait...",
      "LicenseValidation":"License Validation",
      "Version":"Version",
      "https":"https://hr365.us/",
      "ClosePopupModal":"Close popup modal",
  
      ////Add bulk users
      "EmailID":"EmailID",
      "UserDetails":"User-Details-",
      "csv":".csv",
      "InstructionBulkAddUsers":"Instruction- Bulk Add Users",
      "AddMultipleRecordsUpTo100RecordsRerFile":"Add multiple records upto 100 records per file.",
      "AddValidUserEmailIdWhichAreAvailableInM365":"Add valid user email id(s) which are available in M365.",
      "ForM365UsersNoNeed":"For M365 users, no need to fill department columns details in the file,these details are being pulled from M365 automatically.",
      "SucessfullyAddedUsers":"Sucessfully Added Users",
      "SomethingWentWrong":"Something went wrong..!",
      "ImportFileAddUsers":"Please import file to add users!",
      "FilesCsvXlsXlsxType":"Files should only be of .csv, .xls, .xlsx type",
      "SkippedDueMissingMandatoryFields":"Item skipped due to missing mandatory fields..!",
      "ImportSampleFile":"Import Sample File",
      "FillTheTeams":"Please Fill The Teams",
      "FillMainService":"Please Fill The Main service",
      "Restrictedaccess":"Restrictedaccess",
      "hideMBCancel3":"hideMBCancel3",
      "GlobalaccessI":"Globalaccess",
      "TeamaccessI":"TeamaccessI",
      "TeamaccessII":"TeamaccessII",
      "GlobalAess":"Global Access",
      "LimitedVersionThisApplicationYouUseUpto3User":"You are using a Limited version of this application you can use upto 3 users. If you want to add more users please purchase the app from this link&nbsp;",
      "here":"here",
      "LimitedVersionThisApplicationYouUseUptoUserLimit":"You are using a Standard version of this application you can use upto {Userlimit} users. If you want to add more users please purchase the app from this link&nbsp;",
      "PlusVersionThisApplicationYouUseUptoUserLimit":"You are using a Plus version of this application you can use upto {Userlimit} users. If you want to add more users please purchase the app from this link&nbsp;",
      "PremieunVersionThisApplicationYouUseUptoUserLimit":"You are using a Premium version of this application you can use upto {Userlimit} users. If you want to add more users please purchase the app from this link&nbsp;",
      "EnterpriseVersionThisApplicationYouUseUptoUserLimit":"You are using a Enterprise version of this application you can use upto {Userlimit} users. If you want to add more users please purchase the app from this link&nbsp;",
      "CloseTicket":"Close Ticket",
      "SurveyResponses":"Survey Responses",
      "TicketTitleCanEditedBy":"Ticket Title Can be Edited By",
      "AllowUsers":"Allow Users To",
      "TicketProperties":"Ticket Properties",
      "CompactView":"Compact View",
      "NormalView":"Normal View",
      "Integrations":"Integrations",
      "Features":"Features",
      "UsersRolesAndPermissions":"Users, Roles and Permissions",
      "AddEditUsers":"Add/Edit Users",
      "AddEdit":"Add/Edit",
      "AdvancePermissions":"Advance Permissions",
      "IntegrateAssetManagement365":"Integrate with Asset Management 365",
      "Notifications":"Notifications",
      "TicketCustomization":"Ticket Customization",
      "CustomForms":"Custom Forms",
      "MergeTickets":"Merge Tickets",
      "SplitTickets":"Split Tickets",
      "ReviewTicket":"Review Ticket",
      "EscalateTickets":"Escalate Tickets",
      "CreateTicketsAutomatically":"Create Tickets Automatically",
      "AutoCloseTickets":"Auto Close Tickets",
      "AutoAssignTickets":"Auto Assign Tickets",
      "SubTickets":"Sub Tickets",
      "TicketAgingReports":"Ticket Aging Reports",
      "CustomColumns":"Custom Columns",
      "ColumnSettings":"Column Settings",
      "DefineSLAPolicies":"Define SLA Policies",
      "ApplySLAPolicies":"Apply SLA Policies",
      "TimeTracking":"Time Tracking",
      "RemoveCustomWebpartCSS":"Remove Custom Webpart CSS",
      "HideWebpartTitleSharepointPage":"Hide Webpart Title on Sharepoint Page",
      "HideSideNavigationPanelSharepointPage":"Hide Side Navigation Panel on Sharepoint Page",
      "GeneralSettings":"General Settings",
      "DateFormat":"Date Format",
      "Color":"Color",
      "DisplayResolvedTabHomePage":"Display Resolved Tab On Home Page",
      "DisplayHelpPage":"Display Help Page",
      "NamingConvention":"Naming Convention",
      "RecycleBin":"Recycle Bin",
      "UsersRolesandPermissions":"Users Roles and Permissions",
      "Feature":"Feature",
      "SLAPolicy":"SLA Policy",
      "PleaceSelectTeams":"Pleace Select Teams",
      "PleaceSelectServices":"Pleace Select Services",
      "PleaceSelectRequestType":"Pleace Select Request Type",
      "PleaceSelectSLAPolicy":"Pleace Select SLA Policy",
      "B":"B",
      "AM":"AM",
      "PM":"PM",
      "ActiveStatus":"Active Status",
      "AddBusinessHours":"Add Business Hours",
      "PleaseEnterBusinessHoursName":"Please enter business hours name",
      "new":"new",
      "Pointscale":"Point scale",
      "DDMMYYYY":"DD/MM/YYYY",
      "MMDDYYYY":"MM/DD/YYYY",
      "YYYYMMDD":"YYYY/MM/DD",
      "YYYYDDMM":"YYYY/DD/MM",
      "DDMMMYYYY":"DD/MMM/YYYY",
      "DDMMMYYYY":"DD-MMM-YYYY",
      "AutoCloseTicketsinHrs":"Auto Close Tickets in Hrs",
      "NotePleaseUploadLogoOf150X60PxSize":"Note: Please upload logo of 150 X 60 px size with same aspect ratio and use transparent or white background for better viewing experience.",
      "CroppedImage":"Cropped Image",
      "AddSLAPolicies":"Add SLA Policies",
      "EditSLAPolicies":"Edit SLA Policies",
      "ChoicesSeparatedWithComma":" Please mention your choices separated with comma (,)",
      "Text":"Text",
      "SingleLineOfText":"Single line of text",
      "Note":"Note",
      "MultipleLinesOfText":"Multiple lines of text",
      "Number":"Number",
      "DateTime":"Date & Time",
      "Link":"Link",
      "TicketDescriptionI":"Ticket Description",
      "TicketPropertyI":"Ticket Property",
      "SelectAnOption":"Select an option",
      "TeamsMembers":"Teams Members",
      "TeamsSupervisors":"Teams Supervisors",
      "ReportsWillSenddefinedAddCCUsersWithSeparated":"'Reports will be send to defined CC users. Add CC users with ; separated'",
      "SendAgingReportsToCC":"Send aging reports to CC :",
      "EnterEmailAddress":"'Enter the Email Address",
      "AlreadyUpdated":"Already Updated!!",
      "Mins":"Mins",
      "Hrs":"Hrs",
      "Mos":"Mos",
      "CalendarHours":"Calendar Hours",
      "BusinessHours":"Business Hours",
      "EnableSLA":"Enable SLA",
      "ResponseWithin":"Response within",
      "ResolveWithin":"Resolve within",
      "OperationalHours":"Operational Hours",
      "Escalation1":"Escalation 1",
      "Escalation2":"Escalation 2",
      "Alert":"Alert",
      "SLACalculation":"SLA Calculation",
      "IntialResponseSLA":"Intial Response SLA",
      "TicketAssignTime":"Ticket Assign Time",
      "TicketCreationTime":"Ticket Creation Time",
      "ResolveTimeSLA":"Resolve Time SLA",
      "Level1EmailNotification":"Level 1 Email Notification",
      "Level2EmailNotification":"Level 2 Email Notification",
      "AssignTicketsAgentInCircularFashion":"Assign Tickets Agent In Circular Fashion",
      "RoundRobin":"Round Robin",
      "WeightedRoundRobin":"Weighted Round Robin",
      "FeatureTooltip1":"Assign the tickets to the agents who has least tickets. Further select the next agent with least ticket, also it wont assign simultaneously two tickets to the same person.",
      "Configure":"Configure",
      "MakeTimeTrackingMandatory":"Make Time Tracking Mandatory",
      "DisplayHelpPageforUsersInSideNavigationPanel":"Display Help Page for Users in Side Navigation Panel",
      " IntegrateAssetManagement365WithHelpdesk365":" Integrate Asset Management 365 with Helpdesk 365",
      "MailBoxSubText":"By enabling this settings, it will send all the emails through power automate, please ensure that you have enough API call limits(usually you get 2000 calls including all operations in 24 hrs)",
      "MailboxManagers":"Mailbox Managers ",
      "HelpdeskPremiumFeature":" This is a helpdesk premium feature, to add/change ticket mailbox id please write to appsupport@hr365.us ",
      "SendallEmailsFromHelpdeskMailbox":"Send all emails from Helpdesk mailbox",
      "PleaseaddDomains":"Please add domains (separated by coma) here to accept emails to create tickets. Add same domains in mailbox rule to move tickets in 'Ticket' folder.",
      "ExternalDomainsEmailNotification":"For these external domains the email notification will be triggered.",
      "TicketMailboxTabOnHomepage":"This is an add-on role and it enables view 'ticket mailbox' tab on homepage.",
      "AddManagerMail":"Add Manager Mail",
      "HDUserListForAddOnRole":"You can select one of the user from HD user list for add on role.",
      "RenameTeamsTitle":"Rename Teams Title",
      "RenameServiceTitle":"Rename Service Title",
      "RenameSubServiceTitle":"Rename Sub Service Title",
      "NameInNewTicketPage":"Name In New Ticket Page",
      "YouHaveExceededLimitOfCustomColumn":"You have exceeded the limit of Custom Column!",
      "Category":"Category",
      "PleaseMentionYourChoicesSeparatedWithComma":"Please mention your choices separated with comma (,)",
      "SelectColumn":"Select Column",
      "SubColumnName":"Sub Column Name",
      "SubColumnType":"Sub Column Type",
      "ColumnValues":"Column Values",
      "SubColumnValues":"Sub Column Values",
      "PageNotFound":"Page Not Found",
      "TeamAlreadyExisted":"Team already existed!",
      "TeamsHepldeskPhoneNo":"Teams Hepldesk Phone No.",
      "DepartmentHelpdeskPhoneNo":"Department Helpdesk Phone No.",
      "Restore":"Restore",
      "Justnow":"Just now",
      "SecondsAgo":" seconds ago",
      "MinutesAgo":" minutes ago",
      "HoursAgo":" hours ago",
      "DaysAgo":" days ago",
      "MonthsAgo":" months ago",
      "YearsAgo":" years ago",
      "PolicyName":"Policy Name",
      "PolicyDescription":"Policy Description",
      "AddStatus":"Add Status",
      "Name":"name",
      "Code":"code",
      "PleaseFillThe":"Please fill the",
      "AreYouSureWantToDeleteThis":"Are you sure want to delete this ",
      "NewTeam":"New Team",
      "NewEscTeam":"New Esc Team",
      "AddEscalate":"Add Escalate",
      "SLACalculations":"SLA Calculations",
      "FirstLevel":"First Level",
      "SecondLevel":"Second Level",
  
  
      
  
  
  
  
  
  
    }
  export default english