declare interface IHelpDeskWebPartStrings {
  Send: string;
  Replyseemstobeblankdoyouwanttosend: ReactNode;
  UnassignedTicketCannotBeClosed: any;
  Helppage: string;
  Close: string;
  S1: any;
  PleaseEnterValidLicenseKey: any;
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  //Teams Component
  TextFieldName: string;
  TextFieldCode: string;
  TextFieldSupervisor: string;
  TextFieldTeamMembers: string;
  TextFieldDefaultTeam: string;
  EditColumn: string;
  PleaseProvideatLeastColumnName:string;
  ColumnAlreadyExists:string;
  Save: string;
  SaveAprroval:string;
  New: string;
  Edit:string;
  Main:string;
  Members:string;
  View:string;
  AddMore:string;
  Refresh:string;
  EnterNamesorEmailadresses: string;
  Filterbyname: string;
  Addbutton:string;
  Action: string;
  Update: string;
  EditTeams: string;
  AddTeams:string;
  AddPhone:string;
  EditPhone:string;
  EditCannedResponse:string;
  EditMyCannedResponse:string;
  EditMySignature:string;
  //
  DateFormats:string;
  RenameDisplayTitle:string;
  RenameCompanyName:string;
  RenameTicketTitle:string;
  SurveyLinkValidation:string;
  TicketsCanbeDeletedBy:string;
  Admin:string;
  Agent:string;
  IntegrateAssetManagementPluswithHelpdeskPlus:string;
  codeasticketsuffix:string;
  Displayresolvedtabsinhomepage:string;
  EnableTicketMailbox:string;
  AutoCloseTickets:string;
  AutoAssignTickets:string;
  Allowagentstosettheiravailability:string;
  SubjectLineKeywords:string;
  BodyLineKeywords:string;
  ExcludeAgentsfromAutoAssign:string;
  UnAvailableUsers:string;
  BrandLogo:string;
  CustomNote:string;
  UploadLogo:string;
  Crop:string;
  SaveLogo:string;
  DarkMode:string;
  SideNavBarHide:string;
  HideCommandBar:string;
  HideWebPartTitle:string;
  HideTopCommandBarTooltip:string;
  //Web form fields
  AllowUserstosetthe:string;
  Allowusertosetthepriority:string;
  Allowusertosettherequesttype:string;
  Allowusertosettheservice:string;
  AllowusertosettheRequest: string;
  AllowusertosettheTitle:string;
  //
  Home:string;
  Settings:string;
  Help:string;
  Dashboard:string;
  Reports:string;
  CustomSettings:string;
  //Homepage
  AddNewTicket:string;
  NewApprovalWorkflow:string;
  Approval:string;
  SyncMailbox:string;
  NewTicket:string;
  Unassigned:string;
  Show:string;
  Tickets:string;
  Search:string;
  Previous:string;
  Next:string;
  CommentPanel:string;
  TeamsTickets:string;
  TeamsClosed:string;
  TicketMailbox:string;
  MyTickets:string;
  RequestedByMe:string;
  MyClosed:string;
  MyResolved:string;
  TeamsResolved:string;
  Report:string;
  Resolvedby:string;
  ResolvedDate:string;
  Showing:string;
  Of:string;
  Pages:string;
  to:string;
  Items:string;
  Entries:string;

  Teams:string;
  TicketId:string;
  Title:string;
  Status:string;
  Priority:string;
  RequestedBy:string;
  AssignedTo:string;
  CreatedDate:string;
  CreatedBy:string;
  Agehm:string;
  Age:string;
  Action:string;
  ClosedDate:string;
  Days:string;
  ClosedBy:string;
  Form:string;
  Subject:string;
  Body:string;
  SyncMailbox:string;
  Services:string;
  RequestType:string;
  Requester:string;
  Submit:string;
  TicketDescreption:string;
  Low:string;
  Medium:string;
  High:string;
  Urgent:string;
  Question:string;
  Problem:string;
  Incident:string;
  Request:string;

  policyName:string;
  defineName: string;

  AddNew:string;
  GlobalCannedResponse:string;
  ShowEntries:string;
  Yes:string;
  No:string;
  MyCannedResponse:string;
  MySignature:string;
  SignatureMessage:string;
  EditRecords:string;
  AddCannedResponse:string;
  SomethingWentWrong:string;
  TitleAlreadyExists:stringl;
  EnterTitle:string;
  SavedSuccessfully:string;
  CannedResponseTitle:string;
  GlobalCannedResponseTitle:string;
  GlobalCannedMessage:string;
  PleaseenterglobalCannedResponseTitle:string;
  PointScale:string;

  MyCannedResponse:string;
  MyCannedResponseTitle:string;
  MyCannedMessage:string;

  Choice:string;

  MySignature:string;
  MySignatureTitle:string;
  SignatureTitle:string;
  DeleteAlertMessage:string;
  DeleteAlertMessagepolicy:string;
  DeleteAlertMessageCustomColumn:string;
  DeleteAlertMessagestatus:string;
  DeleteAlertMessageservice:string;
  DeleteAlertMessagepriority:string;
  DeleteAlertMessageteam:string;
  DeleteAlertMessageColumn:string
  DeleteAlertMessageRequest:string;
  DeleteAlertMessageBusinessHour:string;
  DeleteAlertMessagemailbox:string;
  DeleteAlertMessageTeams:string;
  AreYouSureyouwanttomergeticket:string;
  NewSurvey:string;
  EditSurvey:string;
  EmailsSentAfterATicketIsClosed:string;
  EmailsSentAfterATicketIsResolved:string;
  AllowAgentsToSendSurveyLink:string;
  PleaseProvideaSurveyName:string;
  Satisfied:string;
  MostlySatisfied:string;
  SomewhatSatisfied:string;
  Fair:string;
  SomewhatDissatisfied:string;
  MostlyDissatisfied:string;
  Dissatisfied:string;
  TeamsCodeasTicketSuffix:string;
  AutoAssignMethod:string;
  SideNavigationTheme:string;
  DisableCustomWebpartCss:string;
  HideWebpartTitle:string;
  HideSideNavigationPanel:string;
  PleaseEnsureThatIntegrationRequiresexternaldatabasePathtobeenabledinAssetManagement:string;
  PleaseProvideatLeastOneChoice:string;
  SurveyName:string;
  CustomerSatisfactionSurvey:string;
  QuestionMessage:string;
  SurveyQuestion:string;
  SurveyPlaceholder:string;
  ThankyouPage:string;
  YourPortalLayoutwillbeappliedtoThisPage:string;
  ThankyouMessageforCustomerSatisfactionSurvey:string;
  ThankyouforyourValueableFeedback:string;
  IncludeCommentsBox:string;

  WhichEmailsshouldhavetheSatisfactionSurveyLink:string;
  Cancel:string;
  CannedResponse:string;
  Add:string;
  HumanResources:string;
  InformationTechnology:string;
  Support:string;
  SalarySlip:string;
  AddressChange:string;
  Office365:string;
  HardwareIssue:string;
  Pending:string;
  Resolved:string;
  WaitingOnCustomer:string;
  WaitingonThirdParty:string;
  Closed:string;
  Open:string;
  UpdateAndsetasPending:string;
  UpdateAndsetasResolved:string;
  UpdateAndsetasClosed:string;
  UpdateAndsetasWaitingonCustomer:string;
  UpdateAndsetasWaitingonThirdParty:string;
  PleaseAssignTheTicketToMerge:string;
  AreYouSureYouWantToSplitTheTicket:string;
  AreYouSureYouWantToCreateANewTicket:string;
  PleaseentermyCannedResponsetitle:string;
  PleaseEnterthePhoneNumber:string;
  PleaseProvideRequestType:string;
  PleaseProvideatLeastOneService:string;
  PleaseEnterMyCannedResponseTitle:string;
  AbovePriorityalreadyexistsPleaseAddanewpriority:string;
  AboveCustomFormisAlreadyExisting:string;
  AbovePriorityalreadyexistsPleaseAddanewSubService:string;
  Pleaseprovideavalidpriority:string;
  PleaseProvideanewvalidrequesttype:string;
  PleaseProvidePriority:string;
  EditServices:string;
  Pleaseentertheteamname:string;
  Pleaseentertheteamcode:string;
  EditEmailBody:string;
  ModifiedBy:string;
  Reply:string;
  AddPrivateNote:string;
  Consult:string;
  Transfer:string;
  Merge:string;
  Split:string;
  Create:string;
  Attachment:string;
  AttachmentTitlle:string;
  Discard:string;
  Type:string;
  PropertiesHelpTitle:string;
  TicketHistory:string;
  Clickhere:string;
  ContactDetails:string;
  EmailId:string;
  PhoneNum:string;
  Job:string;
  RecentTickets:string;
  Ok:string;
  Properties:string;
  OldValue:string;
  NewValue:string;
  ModifiedOn:string;

  CurrentWeek:string;
  LastWeek:string;
  CurrentMonth:string;
  LastMonth:string;
  PreviousMonth:string;
  All:string;
  ModifiedDate:string;
  Positive:string;
  Neutral:string;
  Negative:string;
  Total:string;
  From:string;
  To:string;
  Year:string;
  Quarter:string;
  Month:string;
  Filteroption:string;
  OpenVSClosed:string;
  TotalTicketStatus:string;
  AgentReport:string;
  TotalTickets:string;
  NoDataAvailable:string;
  CustomerSatisfaction:string;
  NoDataToDisplay:string;
  OrderTicketFields:string;
  TicketNameTictle:string;
  EntertheTicketName:string;
  SequenceTitle:string;
  TicketDescription:string;
  TicketProperty:string;
  SubColumnValues:string;
  UseTeamsCodeasTicketSuffix:string;
  EnableSubTicket :string;
  EnableTimeTracking:string;
  Pleaseenterbusinesshoursname:string;
  ExporttoExcel:string;
  Delete:string;
  Assigned:string;
  Active:string;
  Placeholders:string;
  EmailSubject:string;
  TicketFields:string;
  RequesterName:string;
  RequesterEmail:string;
  EmailBody:string;
  Trigger:string;
  IsActive:string
  Assignee:string;
  Supervisor:string;
  RenameApplicationTitle:string;

  Description:string;
  TicketURL:string;
  LastPublicComment:string;
  AgentName:string;
  AgentEmail:string;
  SatisfactionSurvey:string;
  MergeTicketID:string;
  SplitTicketID:string;
  TicketType:string;
  SaveAndAdd:string;
  SatisfactionSurveyStarRating:string;

  Select:string;
  Default:string;
  TeamsName:string;
  TeamName:string;
  AddServices:string;
  NewServices:string;
  DefaultService:string;
  TeamsCode:string;
  TeamCode:string;
  PleaseProvideatLeastOneService:string;
  RolesandScopes:string;
  EntereduseralreadyexistsPleaseaddaNewUser:string;

  EditPhones:string;
  TeamsHelpDeskPhoneNumber:string;
  AddedSuccessfully:string;
  UpdatedSuccessfully:string;
  DeletedSuccessfully:string;
  PleaseFillTheColumnName:string;
  DataSavedSuccessfully:string;
  PleaseProvideatLeastOneStatus:string;
  EditStatus: string;
  PleaseFillTheRequiredFields:string;
  PleaseAddOnePriority:string;
  DefaultRequestType:string;
  AddNewRequestType:string;
  AddRequestType:string;
  ErrorWhileSavingDataPleaseTryAgainAfterSometime:string;
  SavingPleaseWait:string;
  DefaultStatus:string;
  DefaultRequest:string;
  AddPriority:string;
  EditRequestType:string;
  PriorityType:string;
  ColumnName:string;
  Type1: string;
  ColCategory: string;
  ColActive: string;
  SubColumn:string;
  AddNewPriority:string;
  AddNewStatus:string;
  DefaultType:string;
  DefaultPriorityType: string;
  EditPriority:string;
  TicketName:string;
  TicketPrefix:string;
  EnterTicket:string;
  TeamAlreadyExists:string;
  On:string;
  Off:string;
  InfoTitle:string;
  NoOfDaysToLinkExpire:string;
  CompanyName:string;
  Use:string;

  ManagerMailbox:string;
  CreateAutomaticTickets:string;
  TicketMailBox:string;
  infoTitleTicketMailBox:string;
  AllowedDomains:string;
  InfoTitleAllowedDomains:string;
  AllowedExternalDomains:string;
  MailboxManager:string;
  InfoTitleMailboxManager:string;
  RestordSuccessfully:string;
  InfoTitleExternalDomains:string;
  EditUsers:string;
  AddUsers:string;
  AddBulkUsers: string;
  ManagerEmail:string;
  JobTitle:string;
  Role:string;
  Email:string;
  GlobalAccess:string;
  TeamAccessI:string;
  TeamAccessII:string;
  RestrictedAccess:string;
  EnterName:string;
  Roles:string;
  RolesAndScopes:string;
  User:string;
  SelectTeams:string;
  SelectAgent:string;
  SelectStatus:string;
  Today:string;
  LastDay:string;
  SelectPriority:string;
  SelectRequestType: string;
  GeneralSetting:string;
  Users:string;
  WebFormFields:string;
  BusinessHours:string;
  TicketFields:string;
  TicketSequence:string;
  SupportChannel:string;
  HelpDeskMailBox:string;
  Phone:string;
  HelpDeskProductivity:string;
  CannedResponses:string;
  EmailNotification:string;
  CustomerSatisfaction:string;
  CusSatRating:string;
  Comments:string;

  SiteTheme:string;
  LightMode:string;
  RemoveCustomWebpartCss:string;
  EditBusinessHours:string;
  Sunday:string;
  Monday:string;
  Tuesday:string;
  Wednesday:string;
  Thursday:string;
  Friday:string;
  Saturday:string;
  Sunday:string;
  HelpdeskHours:string;
  Ticketsspace:string;
  Closedspace:string;
  Resolvedspace:string;
  Selectspace:string;
  DeleteAlertMessageTicket:string;
  TimeTrack:string;
  EmptytimeTrackBox:string;
  Timetrackingismandatory:string;
  Areyousureyouwanttostoptimetracking:string;
  Unassignedticketnotresolved:string;
  Unassignedticketnotclosed:string;
  UpdateTitle:string;
  SelectWorkingDaysHours:string;
  hrs24x7Days:string;
  PleaseEnterGlobalCannedResponseTitle:string;
  PleaseEnterMyCannedResponseTitle : string;
  PleaseEnterSignatureTitle : string;
  SyncfromM365:string;
  ToupdateuserpropertiesfromM365clickheretoSync:string;
  UserIconTitle:string;
  TicketFieldTitle:string;
  SolidUp:string;
  downloadtitle:string;
  DeleteAlertMessage2:string;
  ClearFilters:string;
  Department: string;
  ManagerName: string;
  Location:string;
  AddBulk:string;
  ServiceName: string;
  SettingSavedSuccesfully:string;
  SLAPoliciesApplied:string;
  SubServiceName:string;
  SubTicket:string;
  Escalate:string;
  Review:string;
  PleaeEntertitle:string;
  Validate:string;
  TicketPropertiescanhideShowintheUsersCommentPage: string;
  TicketPropertiescanhideShowintheMembersCommentPage: string;
  SyncUserPropertiesfromM365: string;
  AssignedAssets:string;
  AssetDeailsHeading:string;
  Cost:string;
  ResidualCost:string;
  BarcodeOrQRCode:string;
  AssetId:string;
  Documents:string;
  Additional:string;
  CurrentUser:string;
  UserLocation:string;
  UserDepartment:string;
  ExportQRCodes:string;
  ExportBarcodes:string;
  OrganizationName:string;
  ReturnDate:string;
  AssignDate:string;
  NumberOnly:string;
  CommaSpearate:string;
  General:string;
  Print:string;
  AssetNameErrorMessage:string;
  AssetExpiryNotification:string;
  UploadCommercialDocument:string;
  AssetName:string;
  MyRequestes:string;
  Requests:string;
  Knowledgebase:string;
  Satisfactionsurvey:string;

  //Feedback submission
  Feedbacksubmittedsuccessfully: string;
  Approved: string;
  Approve:string;
  Reject: string;
  Thisarticlehasbeenapprovedsuccessfully: string;
  Thisarticlehasbeenrejected: string;

  // Approver Workflow
  WorkflowName: string;
  Teams: string;
  ApprovalType: string;


  ///// For Language Part

   ////Deshbaord
  Satisfied:string;
  MostlySatisfied:string;
  MostlySatisfied:string,
  MostlySatisfied:string,
  SomewhatSatisfied:string,
  Dissatisfied:string,
  Mostlydissatisfied:string,
  Mostlydissatisfied:string,
  SomewhatDissatisfied:string,
  Portal:string,
  Email:string,
  Phone:stirng,
  Forms:string,
  Bot:string,
  Others:string,
  CurrentWeekForkey:string,
  CurrentMonthForKey:string,
  CurrentQuarterForKey:string,
  CurrentQuarter:string,
  CurrentYearForkey:string,
  CurrentYear:string,
  LastWeekForkey:string,
  LastMonthForkey:string,
  LastQuarterForkey:string,
  LastQuarter:string,
  LastYear:string,
  LastYearForkey:string,
  CustomDateForkey:string,
  CustomDate:strings,
  CustomYear:string,
  CustomYearForkey:string,
  CustomQuarter:string,
  CustomQuarterForkey:string,
  CustomMonth:string,
  CustomMonthForkey:string,
  CustomWeek:string,
  CustomWeekForkey:string,
  January:string,
  February:string,
  March:string,
  April:string,
  May:string,
  June:string,
  July:string,
  August:string,
  September:string,
  October:string,
  November:string,
  December:string,
  LastWeekForkey:string,
  CurrentMonthForkey:string,
  Created:string,
  Escalated:string,
  TicketsThisMonth:string,
  AllTeams:string,
  SLAResponseAverage:string,
  SLAResponseWeekdays:string,
  TicketsByType:string,
  OpenTicketsDepartment:string,
  TicketsPriority:string,
  TicketsSource:string,
  TimeTrack:string,
  SLAResolveAverage:string,
  SLAResolveWeekdays:string,
  ApplyFilter:string,
  Filterapplied:string,
  SelectStartDate:string,
  SelectEndDate:string,
  selectleastonefield:string,
  SelectOption:string,
  SelectDatebtu:string,
  StartDate:string,
  EndDate:string,
  SelectYear:string,
  SelectQuarter:string,
  SelectMonth:strings,

  ///Help Page
  LicenseType:string,
  Expired:string,
  ValidTill:string,
  LicenseTypeExpired:string,
  LicenseTypeLimited:string,
  LicenseTypeStandardPerpetual:string,
  LicenseTypeStandardExpired:string,
  LicenseTypeStandard:string,
  LicenseTypePlusPerpetual:string,
  LicenseTypePlusExpired:string,
  LicenseTypePlus:string,
  LicenseTypePremiumPerpetual:string,
  LicenseTypePremiumExpired:string,
  LicenseTypePremium:string,
  LicenseTypeEnterprisePerpetual:string,
  LicenseTypeEnterpriseExpired:string,
  LicenseTypeEnterprise:string,
  Inputlicensekey:string,
  HD365:string,
  LicenseValidationSuccessful:string,
  EnterLicenseKey:string,
  ValidatedSuccessfully:string,
  ContactUs:string,
  PrivacyPolicy:string,
  FAQ:string,
  ProductActivation:string,
  PleaseWait:string,
  LicenseValidation:string,
  Version:string,
  https:string,
  ClosePopupModal:string,
  EmailID:string,
  UserDetails:string,
  csv:stirng,
  InstructionBulkAddUsers:string,
  AddMultipleRecordsUpTo100RecordsRerFile:string,
  AddValidUserEmailIdWhichAreAvailableInM365:string,
  ForM365UsersNoNeed:string,
  SucessfullyAddedUsers:string,
  SomethingWentWrong:strings,
  ImportFileAddUsers:string,
  FilesCsvXlsXlsxType:strings,
  SkippedDueMissingMandatoryFields:string,
  ImportSampleFile:string,
  FillTheTeams:string,
  FillMainService:string,
  Restrictedaccess:string,
  hideMBCancel3:string,
  GlobalaccessI:string,
  TeamaccessI:string,
  TeamaccessII:strings,
  GlobalAess:string,
  LimitedVersionThisApplicationYouUseUpto3User:string,
  here:string,
  LimitedVersionThisApplicationYouUseUptoUserLimit:string,
  PlusVersionThisApplicationYouUseUptoUserLimit:string,
  PremieunVersionThisApplicationYouUseUptoUserLimit:string,
  EnterpriseVersionThisApplicationYouUseUptoUserLimit:string,
  CloseTicket:string,
  SurveyResponses:string,
  TicketTitleCanEditedBy:string,
  AllowUsers:string,
  TicketProperties:string,
  CompactView:string,
  NormalView:string,
  Integrations:string,
  Features:string,
  UsersRolesAndPermissions:string,
  AddEditUsers:string,
  AddEdit:string,
  AdvancePermissions:string,
  IntegrateAssetManagement365:string,
  Notifications:string,
  TicketCustomization:string,
  CustomForms:string,
  MergeTickets:string,
  SplitTickets:string,
  ReviewTicket:string,
  EscalateTickets:string,
  CreateTicketsAutomatically:string,
  AutoCloseTickets:string,
  AutoAssignTickets:string,
  SubTickets:string,
  TicketAgingReports:string,
  CustomColumns:string,
  ColumnSettings:string,
  DefineSLAPolicies:string,
  ApplySLAPolicies:string,
  TimeTracking:string,
  RemoveCustomWebpartCSS:string,
  HideWebpartTitleSharepointPage:string,
  HideSideNavigationPanelSharepointPage:string,
  GeneralSettings:string,
  DateFormat:string,
  Color:string,
  DisplayResolvedTabHomePage:string,
  DisplayHelpPage:string,
  NamingConvention:string,
  RecycleBin:string,
  UsersRolesandPermissions:string,
  Feature:string,
  SLAPolicy:srting,
  PleaceSelectTeams:string,
  PleaceSelectServices:string,
  PleaceSelectRequestType:string,
  PleaceSelectSLAPolicy:string,
  B:string,
  AM:string,
  PM:string,
  ActiveStatus:string,
  AddBusinessHours:string,
  PleaseEnterBusinessHoursName:string,
  new:string,
  Pointscale:string,
  DDMMYYYY:string,
  MMDDYYYY:string,
  YYYYMMDD:string,
  YYYYDDMM:string,
  DDMMMYYYY:string,
  DDMMMYYYY:string,
  AutoCloseTicketsinHrs:string,
  NotePleaseUploadLogoOf150X60PxSize:string,
  CroppedImage:string,
  AddSLAPolicies:string,
  EditSLAPolicies:string,
  ChoicesSeparatedWithComma:string,
  Text:sting,
  SingleLineOfText:string,
  Note:string,
  MultipleLinesOfText:string,
  Number:strings,
  DateTime:string,
  Link:string,
  TicketDescriptionI:string,
  TicketPropertyI:string,
  SelectAnOption:string,
  TeamsMembers:string,
  TeamsSupervisors:string,
  ReportsWillSenddefinedAddCCUsersWithSeparated:string,
  SendAgingReportsToCC:string,
  EnterEmailAddress:string,
  AlreadyUpdated:string,
  Mins:string,
  Hrs:string,
  Mos:string,
  CalendarHours:string,
  BusinessHours:string,
  EnableSLA:string,
  ResponseWithin:string,
  ResolveWithin:string,
  OperationalHours:string,
  Escalation1:string,
  Escalation2:string,
  Alert:string,
  SLACalculation:string,
  IntialResponseSLA:string,
  TicketAssignTime:string,
  TicketCreationTime:string,
  ResolveTimeSLA:string,
  Level1EmailNotification:string,
  Level2EmailNotification:string,
  AssignTicketsAgentInCircularFashion:string,
  RoundRobin:string,
  WeightedRoundRobin:string,
  FeatureTooltip1:string,
  Configure:string,
  MakeTimeTrackingMandatory:string,
  DisplayHelpPageforUsersInSideNavigationPanel:string,
  IntegrateAssetManagement365WithHelpdesk365:string,
  MailBoxSubText:string,
  MailboxManagers:string,
  HelpdeskPremiumFeature:string,
  SendallEmailsFromHelpdeskMailbox:string,
  PleaseaddDomains:string,
  ExternalDomainsEmailNotification:string,
  TicketMailboxTabOnHomepage:string,
  AddManagerMail:string,
  HDUserListForAddOnRole:string,
  RenameTeamsTitle:string,
  RenameServiceTitle:string,
  RenameSubServiceTitle:string,
  NameInNewTicketPage:string,
  YouHaveExceededLimitOfCustomColumn:string,
  Category:string,
  PleaseMentionYourChoicesSeparatedWithComma:string,
  SelectColumn:string,
  SubColumnName:string,
  SubColumnType:string,
  ColumnValues:string,
  SubColumnValues:string,
  PageNotFound:string,
  TeamAlreadyExisted:string,
  TeamsHepldeskPhoneNo:string,
  DepartmentHelpdeskPhoneNo:string,
  Restore:string,
  Justnow:string,
  SecondsAgo:string,
  MinutesAgo:string,
  HoursAgo:string,
  DaysAgo:string,
  MonthsAgo:string,
  YearsAgo:string,
  PolicyName:string,
  PolicyDescription:string,
  AddStatus:string,
  Name:string,
  PleaseFillThe:string,
  Code:string,
  AreYouSureWantToDeleteThis:string,
  NewTeam:string,
  NewEscTeam:string,
  AddEscalate:string,
  SLACalculations:string,
  FirstLevel:string,
  SecondLevel:string,


}

declare module 'HelpDeskWebPartStrings' {
  const strings: IHelpDeskWebPartStrings;
  export = strings;
}
